name: Vendor manifests consumer
description: "Extracts and processes vendor manifests"

inputs:
  repository:
    description: Repository containing vendor manifest(s)
    type: string
    required: true
  artifactory-repo-url:
    description: Target Artifactory repository URL
    type: string
    required: true
  artifactory-user:
    description: Artifactory user
    type: string
    required: false
  artifactory-password:
    description: Artifactory user password
    type: string
    required: false
  ssh-key:
    description: SSH private key (deploy key) for accessing the vendor repository
    required: false
  token:
    description: Personal access-token of the target repository
    required: false

runs:
  using: "composite"

  steps:
    - name: Checkout vendor repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ssh-key: ${{ inputs.ssh-key }}

    - name: Process manifests
      shell: bash
      run: |
        scripts/process-downloads.sh \
        art-user \
        art-password \
        https://art-base-url \
        art-repo
