name: Vendor manifests consumer
description: "Extracts and processes vendor manifests"

inputs:
  repository:
    description: Repository containing vendor manifest(s)
    type: string
    required: true
  ref:
    description: Repository ref (branch, tag, commit)
    type: string
    required: false
  ssh-key:
    description: SSH private key (deploy key) for accessing the vendor repository
    required: false
  artifactory-base-url:
    description: Target Artifactory repository URL
    type: string
    required: true
  artifactory-user:
    description: Artifactory user
    type: string
    required: false
  artifactory-password:
    description: Artifactory user password
    type: string
    required: false
  artifactory-repo:
    description: Artifactory target repository
    type: string
    required: true

runs:
  using: "composite"

  steps:

    - name: Checkout vendor repository
      uses: actions/checkout@v3
      with:
        repository: "${{ inputs.repository }}"
        ref: "${{ inputs.ref }}"
        ssh-key: "${{ inputs.ssh-key }}"

    # - name: checkout 2
    #   shell: bash
    #   run: |
    #     echo "${{ inputs.ssh-key }}" >> ~/.ssh/test-ext-suppliers
    #     mkdir -p ~/.ssh
    #     chmod 700 ~/.ssh

    #     cat <<EOF > ~/.ssh/config
    #     Host github.com-repo-0
    #             Hostname github.com
    #             IdentityFile=~/.ssh/test-ext-suppliers
    #     EOF

    #     git clone git@github.com-repo-0:amoravek/test-vendor-repo.git

    - name: Process manifests
      shell: bash
      run: |
        scripts/process-downloads.sh \
        ${{ inputs.artifactory-user }} \
        ${{ inputs.artifactory-password }} \
        ${{ inputs.artifactory-base-url }} \
        ${{ inputs.artifactory-repo }}
