name: Vendor manifests consumer
description: "Extracts and processes vendor manifests"

inputs:
  repository:
    description: Repository containing vendor manifest(s)
    type: string
    required: true
  ref:
    description: Repository REF
    type: string
    required: false
    default: master
  artifactory-repo-url:
    description: Target Artifactory repository URL
    type: string
    required: true
  artifactory-user:
    description: Artifactory user
    type: string
    required: false
  artifactory-password:
    description: Artifactory user password
    type: string
    required: false
  ssh-key:
    description: SSH private key (deploy key) for accessing the vendor repository
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout vendor repository
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        ssh-key: "${{ inputs.ssh-key }}"

    - name: test
      shell: bash
      run: cat artifacts.yaml
